### PR TITLE
deps: update nomad dependency to v1.6.0-beta.1

### PR DESCRIPTION
**Pull request by shoenig**
Should hopefully fix the CGO problem in https://github.com/hashicorp/nomad-driver-podman/issues/227

### CODE REVIEW

**Review by lgfa29 — APPROVED** [review]
I'm not sure how to test this, but if you need something to smoke test I built some binaries from this branch:
https://github.com/hashicorp/nomad-driver-podman/actions/runs/5480372129

**Comment by shoenig** [comment]
@jdoss if you have access to the artifacts in ^, mind trying against Fedora CoreOS?

**Comment by jdoss** [comment]
@shoenig I was able to test this out this evening on a client node and it worked as expected! Thank you for fixing this. 😄

**Comment by ahjohannessen** [comment]
@shoenig Is a 0.4.3 with this fix soon released?

**Comment by shoenig** [comment]
We'll do a Podman v0.5.0 release as soon as we have Nomad v1.6 GA, which should be in the next day or so.

**Pull request merged**
