### PR TITLE
Added support for using existing network stack

### PR DESCRIPTION
**Pull request by joshiparth1000**
Support for using existing network stack

### CODE REVIEW

**Comment by towe75** [comment]
@joshiparth1000 thank you for your contribution!
I will take a closer look within a few days. Maybe you can check PR #116 in the meantime to see if there is some feature overlap with your work? Both branches enhance the drivers network interoperability.

**Comment by towe75** [comment]
@joshiparth1000 : What about integrating your feature with the existing network_mode driver configuration option. It would build upon the ideas from #116, adding a network_mode=pod:somepod and network_mode=cni:first,second

**Comment by joshiparth1000** [comment]
Yes, that will work as well. I am up for it.

**Comment by shoenig** [comment]
As mentioned in #173 Podman is dropping CNI support in v5.

**Pull request closed without merging**
