### PR TITLE
config: Add ulimit option like docker driver

### PR DESCRIPTION
**Pull request by pabloyoyoista**
I guess the title is self-explanatory. 

The `sliceMergeUlimit` function is adapted from the nomad [docker driver](https://github.com/hashicorp/nomad/blob/main/drivers/docker/driver.go#L1723)

### CODE REVIEW

**Comment by pabloyoyoista** [comment]
This is just a small feature addition which makes this driver slightly closer to docker :) Hopefully it is uncontroversial.

**Comment by pabloyoyoista** [comment]
@towe75 @lgfa29 @jrasell @jazzyfresh friendly ping? :)

**Review by lgfa29 — APPROVED** [review]
Sorry for the delay on getting this reviewed @pabloyoyoista. 

This LGTM, I just pushed a commit to fix the CHANGELOG and add a link to the PR. 

Also, this is kind of annoying, but would you mind opening a PR against the Nomad repo to also document the new config in this page:
https://github.com/hashicorp/nomad/blob/main/website/content/plugins/drivers/podman.mdx

Thanks for the contribution!

**Comment by pabloyoyoista** [comment]
Thank you for the merge! Not fun to duplicate work, but just sent the docs update: https://github.com/hashicorp/nomad/pull/13180

**Pull request merged**
